name: Build and Upload Documentation

on:
  push:
    branches:
      - main
      - 'release/**'
    paths:
      - 'docs/**'
  workflow_dispatch:  # 允许手动触发

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        working-directory: ./docs
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Determine version tag
        id: determine-version
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "VERSION=latest" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" =~ refs/heads/release/(.*) ]]; then
            VERSION=${BASH_REMATCH[1]}
            echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          fi
      
      - name: Build documentation for 52x
        working-directory: ./docs
        run: python generate_docs.py 52x

      - name: Build documentation for 56x
        working-directory: ./docs
        run: python generate_docs.py 56x

      - name: Build documentation for 58x
        working-directory: ./docs
        run: python generate_docs.py 58x

      - name: Build documentation for 55x
        working-directory: ./docs
        run: python generate_docs.py 55x

      - name: Archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: docs-${{ steps.determine-version.outputs.VERSION }}
          path: |
            docs/build_52x/html
            docs/build_56x/html
            docs/build_58x/html
            docs/build_55x/html
          retention-days: 7
      
      - name: Install COSCMD
        run: |
          pip install coscmd

      - name: Configure COSCMD
        run: |
          coscmd config -a ${{ secrets.COS_DOCS_SECRET_ID }} -s ${{ secrets.COS_DOCS_SECRET_KEY }} -b ${{ secrets.COS_DOCS_BUCKET }} -r ${{ secrets.COS_DOCS_REGION }}

      - name: Upload to COS - 52x
        run: |
          VERSION=${{ steps.determine-version.outputs.VERSION }}
          coscmd upload -rs --delete --yes ./docs/build_52x/html/ projects/sdk/$VERSION/sf32lb52x/
          echo "Uploaded documentation for 52x to $VERSION/52x/"

      - name: Upload to COS - 56x
        run: |
          VERSION=${{ steps.determine-version.outputs.VERSION }}
          coscmd upload -rs --delete --yes ./docs/build_56x/html/ projects/sdk/$VERSION/sf32lb56x/
          echo "Uploaded documentation for 56x to $VERSION/56x/"

      - name: Upload to COS - 58x
        run: |
          VERSION=${{ steps.determine-version.outputs.VERSION }}
          coscmd upload -rs --delete --yes ./docs/build_58x/html/ projects/sdk/$VERSION/sf32lb58x/
          echo "Uploaded documentation for 58x to $VERSION/58x/"

      - name: Upload to COS - 55x
        run: |
          VERSION=${{ steps.determine-version.outputs.VERSION }}
          coscmd upload -rs --delete --yes ./docs/build_55x/html/ projects/sdk/$VERSION/sf32lb55x/
          echo "Uploaded documentation for 55x to $VERSION/55x/"